### ISSUE TITLE
Footer Widget Area Not Responding to Column Setting

### ISSUE THREAD

**Issue by keempoo** [aemi-dev/aemi#12] opened 2021-02-12 18:53 UTC
**Describe the bug**
In 
Customizing> Aemi> Widgets

Changing
Footer Widget Area Column Layout (Choose maximum number of column for footer widget area.)

Stays at the defaulted 2-Column

**To Reproduce**
1. Go to 'Customizing> Aemi> Widgets> Footer Widget Area Column Layout, Choose maximum number of column for footer widget area.'
2. Click on 'One Column'
3. Publish

**Expected behavior**
Footer widgets to be listed as one column.

**Screenshots**
If I used the Inspector and change the default to "one-column", it appears correctly, however I do not have the savvy to fix it permanently. 

Default in Inspector is "two-columns"
![image](https://user-images.githubusercontent.com/47604367/107809763-3a11c400-6d31-11eb-9795-514f8d530515.png)

Works if you change the value to "one-columns"
![image](https://user-images.githubusercontent.com/47604367/107810070-b2788500-6d31-11eb-932a-e335f5d8c1e0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Works on mobile because default is single column

**Additional context**
Sorry it's me again. I love the theme! xoxo

**Comment by aemi-dev** [comment] 2021-02-19 01:29
Hi @keempoo ,

I'm really glad to hear again from you, it shows Aemi theme gets some interest and I love that. I'm also sorry you encountered a bug and moreover I'm sorry to tell you I could not reproduce it.

I get a development version of Aemi theme on https://dev.aemi.dev/ website. I turned to One then to Two then back to One column layout and I never encountered such an issue.

Please, can you tell me what version of Aemi Theme you are using ?

I have some dumb recommendations too : clean browser cache (you surely already did that) and clean cache created by any cache plugin on your WordPress website (you surely did it too). I'm waiting for more informations from you to investigate further.

Also, if you like Aemi theme, please feel free to leave a tiny (or complete) review on official WordPress.org theme page : https://wordpress.org/support/theme/aemi/reviews

Best Regards,
Guillaume

**Comment by keempoo** [comment] 2021-02-19 21:10
Ok, let me back up and see what an update of the theme will do for me.

**Comment by aemi-dev** [comment] 2021-02-19 21:13
I think I will mention the breaking changes in the next updates to make it lesser annoying to update 🤔.

**Comment by keempoo** [comment] 2021-03-08 15:35
Hi Guillaume,

Sorry for the late reply. I did manage to update the Aemi theme, but I
still can't get the footer to respond to column customization on
astrosalad.com.  I did have help from a friend who made some adjustments,
but I can't imagine how it would affect the footer. I had him make a custom
page that pulled all the links from the site
https://www.astrosalad.com/links/, and had him add the category
descriptions to pages. His code must not be very clean because on the
update some of the styling got messed up but I can probably undo it.

If you have any inklings as to what it might be, please let me know. I
looked at the dev site and can't figure it out based on that.

**Comment by keempoo** [comment] 2021-03-09 15:44
I fixed it! Just needed to switch default width, clear cache, set it back
clear cache. Not sure why clearing cache without changes didn't work.

**Comment by aemi-dev** [comment] 2021-03-09 16:13
Hi @keempoo ,

Thanks for keeping me up to date with the problem. I already thought that clean cache could fix this bug as said in an earlier answer. Now, with what you said, I think I know where to look for the bug. I'll try to make the theme more reliable in next update. Do not hesitate to reach me if anything goes wrong again.

I'll close this issue now that it is fixed but I'll keep in mind to get rid of this bug.

Kind Regards

Guillaume

**Closed by aemi-dev** 2021-03-09 16:13 UTC
